---
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ensure vim is installed
      package:
        name: vim
        state: present
    - name: Ensure ncdu is installed
      package:
        name: ncdu
        state: present